### PR TITLE
Update from v2022a to v2022c

### PR DESCRIPTION
**Pull request by marcoesters**
Addresses ticket [DSNC-5217](https://anaconda.atlassian.net/browse/DSNC-5217) and makes [DSNC-5210](https://anaconda.atlassian.net/jira/software/c/projects/DSNC/issues/DSNC-5210) obsolete.

### CODE REVIEW

**Comment by ryanskeith** [comment]
LGTM

**Review by varlackc — COMMENTED** [review]
We might want to see if we can build for `windows` and if it is not possible we might need to see how we should deal with that architecture.

**Comment by marcoesters** [comment]
> We might want to see if we can build for `windows` and if it is not possible we might need to see how we should deal with that architecture.

It doesn't build on Windows. It requires too many POSIX APIs to compile, so it has to stay noarch without building on Windows. I added comments to reflect this.

This has exposed other issues with the recipe though, which have now been fixed.

**Review by skupr-anaconda — APPROVED** [review]

**Review by varlackc — COMMENTED** [review]
Historically we have provided support for `tzdata` on windows.
The latest version in defaults is `2022a`. We might have to investigate the best way to address the errors on windows to see what may be causing them and to see if we can find a solution.

**Comment by marcoesters** [comment]
> Historically we have provided support for `tzdata` on windows. The latest version in defaults is `2022a`. We might have to investigate the best way to address the errors on windows to see what may be causing them and to see if we can find a solution.

We provided support on Windows with a `noarch` build, which will still be available. There was no Prefect Windows build in `2022a` - see the commit here: https://github.com/AnacondaRecipes/tzdata-feedstock/commit/db6da8d66c413ddf5618974f816f721b30e7fcf3

Us not having a Windows build is also the reason why the errors in the recipes were never noticed.

I (with the help of @katietz) did investigate the errors and the problem is that `tzdata` uses a lot of POSIX APIs. The solution is to port `tzdata` to use the Windows system APIs. Given the size of the package, this did not seem feasible to us since we would have to keep patching with every update.

**Review by varlackc — COMMENTED** [review]
There is only one more detail, we might want to add the `license_family` other than that everything else looks good. 

https://github.com/AnacondaRecipes/tzdata-feedstock/blob/3fa952b20c91fbff763bf94103e67dd00f20087f/recipe/meta.yaml#L34&L36

**Comment by marcoesters** [comment]
> 

What would the license family be in this case? There are two licenses.

**Pull request merged**
