### PR TITLE
PKG-1377-tzdata-2023-c

### PR DESCRIPTION
**Pull request by JamesRobertsonGames**
[PKG-1377] 

[PKG-1377]: https://anaconda.atlassian.net/browse/PKG-1377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by cbouss — COMMENTED** [review]
Looks good to me but the PR build is missing some architectures for some reason.
It would be good to close/reopen the PR to make sure all 7 architectures can build.

**Review by M-Waszkiewicz-Anaconda — APPROVED** [review]
change license related things as mentioned by linter and is good to go for me

**Comment by skupr-anaconda** [comment]
> Linter check found the following problems:

Address linter checks

**Comment by JamesRobertsonGames** [comment]
> > Linter check found the following problems:
> 
> Address linter checks

I think those have been correctly addressed now - is it to be expected that the linter will pick up the changes and post here again if it has passed or failed? @skupr-anaconda

**Review by skupr-anaconda — APPROVED** [review]
LGTM

**Pull request merged**
