### PR TITLE
tzdata update to 2022f

### PR DESCRIPTION
**Pull request by Arishamays1**
# Tzdata version bump to 2022f
- updated sha256

### CODE REVIEW

**Review by ryanskeith — APPROVED** [review]
These look good to me

**Comment by AndrewVallette** [comment]
I want to note that this is now only built on `linux-64` because **1)** that is all we need for `noarch` :) and **2)** There was an `osx-arm64` issue causing a failure due to an attempted use of the `getrandom` syscall, which does not exist on MacOS. The failure is irrelevant since we don't need this built for that arch.

LGTM!

**Review by AndrewVallette — APPROVED** [review]

**Review by varlackc — COMMENTED** [review]
Since this is a version update, we probably should make the package `architecture specific` instead of `noarch`
https://github.com/AnacondaRecipes/tzdata-feedstock/blob/e78a5ca153bc03a195ef7062111d3c6cd8f78de1/recipe/meta.yaml#L15

**Comment by skupr-anaconda** [comment]
> Since this is a version update, we probably should make the package `architecture specific` instead of `noarch`
> 
> https://github.com/AnacondaRecipes/tzdata-feedstock/blob/e78a5ca153bc03a195ef7062111d3c6cd8f78de1/recipe/meta.yaml#L15

No, `noarch: generic` is correct. But for future package builders, a short comment would be nice to add about why this data package is noarch

**Review by skupr-anaconda — APPROVED** [review]

**Pull request merged**
